project:
  type: website
  output-dir: docs

website:
  title: "Shlok's Jupyter"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Shlok2002
      - icon: linkedin
        href: https://www.linkedin.com/in/shlokkamat/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

