project:
  type: website
  output-dir: docs

website:
  title: "Shlok's Jupyter"
  navbar:
    right:
      - href: about.qmd
        text: About Me
      - icon: github
        href: https://github.com/Shlok2002
      - icon: linkedin
        href: https://www.linkedin.com/in/shlokkamat/
      - text: Website
        href: https://shlok-kamat.github.io/
format:
  html:
    theme: journal
    css: styles.css

editor: visual

